import { Platform, StyleSheet } from "react-native";

const color_list = {
  black: "#000",
  orange: "#e8ab30",
  green: "#49745e",
  green_light: "#49745e35",
  green_dark: "#3a5d4a",
  cream: "#f8f6f1",
  white: "#fff",
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color_list.cream,
    paddingHorizontal: 20,
    marginBottom: 0,
    paddingBottom: 0,
  },
  title: {
    fontWeight: "bold",
    fontSize: 18,
    color: "black",
  },
  sub_title: { fontSize: 16, color: "gray" },
  h_container: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 15,
  },
  shadow: {
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  btn_icon: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: color_list.white,
    justifyContent: "center",
    alignItems: "center",
  },
  new_com_container: {
    borderRadius: 10,
    backgroundColor: color_list.green,
    padding: 20,
    marginBottom: 10,
  },
  new_book_img: {
    width: 120,
    height: 180,
    borderRadius: 8,
  },
  new_book_title: {
    color: color_list.white,
    fontSize: 18,
    fontWeight: "bold",
  },
  new_book_text: {
    color: color_list.white,
    fontSize: 13,
    lineHeight: 16,
  },
  circle_premium: {
    position: "absolute",
    top: -5,
    right: -5,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: color_list.orange,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonStarted: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 30,
    gap: 10,
    minWidth: 200,
  },
  button: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: Platform.OS === "ios" ? 15 : 10,
    paddingHorizontal: Platform.OS === "ios" ? 40 : 0,
    borderRadius: 30,
  },
  buttonText: {
    fontSize: 18,
    fontWeight: "bold",
    color: color_list.green,
    letterSpacing: 0.5,
  },
  container_book_collections: {
    flex: 1,
    marginTop: 0,
  },
  container_book_collections_title: {
    fontSize: 18,
    fontWeight: "bold",
  },
  book_grid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    marginTop: 10,
    paddingBottom: 20,
  },
  book_card: {
    width: "48%",
    backgroundColor: color_list.white,
    borderRadius: 10,
    marginBottom: 15,
    overflow: "hidden",
  },
  book_card_img: {
    width: "100%",
    height: 200,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    backgroundColor: color_list.green_dark,
  },
  circle_premium_small: {
    position: "absolute",
    top: 5,
    right: 5,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: color_list.orange,
    justifyContent: "center",
    alignItems: "center",
  },
  book_card_title: {
    fontSize: 14,
    fontWeight: "bold",
    color: "black",
    marginBottom: 4,
    minHeight: 34,
  },
  book_card_author: {
    fontSize: 12,
    color: "gray",
    marginBottom: 8,
  },
  book_card_footer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  book_card_rating: {
    fontSize: 12,
    color: "black",
    marginLeft: 4,
    fontWeight: "600",
  },
  book_card_views: {
    fontSize: 12,
    color: "gray",
    marginLeft: 4,
  },
});

export { color_list, styles };
